#version 460 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = SSBO_UNIQUE_COUNT_BINDING)  readonly  buffer UniqueCount { uint uniqueCount; };
layout(std430, binding = SSBO_INDIRECT_ARGS_BINDING) writeonly buffer IndirectArg { uvec4 args[]; };

uniform uint localSize;     // per-voxel pass local_size_x (64)

void main(){
    args[0] = uvec4((uniqueCount + localSize - 1u) / localSize, 1u, 1u, 0u);
}
