#version 460 core

layout(local_size_x = 8, local_size_y = 8) in;


layout(binding = 0, rgba32ui) writeonly uniform uimage2D gbufferTexture;

layout(std430, binding = SSBO_OCTREE_BINDING) readonly buffer OctreeBuffer { uvec2 nodes[]; } octree;

uniform uint octreeDepth;
uniform ivec2 screenResolution;
uniform uint primary_raystop;

layout(std140, binding = 0) uniform CameraUniform {
    vec4 position;
    vec4 cameraPlane, cameraPlaneRight, cameraPlaneUp;
} camera;

#include "gbuffer.glsl"
#include "internal.glsl"

void main() {
    ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
    bool inBoundsPix = (pix.x < screenResolution.x && pix.y < screenResolution.y);
    uvec4 gkey = uvec4(0u);

    if (inBoundsPix) {
        vec2 ndc = vec2(
            (float(pix.x) + 0.5) / float(screenResolution.x) * 2.0 - 1.0,
            (float(pix.y) + 0.5) / float(screenResolution.y) * 2.0 - 1.0
        );
        vec3 direction = normalize(
            camera.cameraPlane.xyz
            + ndc.x * camera.cameraPlaneRight.xyz
            - ndc.y * camera.cameraPlaneUp.xyz
        );

        octreeLength = 1u << octreeDepth;

        ray_t ray;
        ray.origin = camera.position.xyz;
        ray.direction = direction;
        ray.inverted_direction = 1.0 / direction;

        hit_t voxel = Raycast(ray, octreeDepth, primary_raystop, 2.0);

        if (voxel.hit && voxel.material != 0u) {
            uint level = max(1u, octreeDepth - uint(findMSB(voxel.size)));
            gkey = PackGBuffer(voxel.position, level, voxel.material, voxel.version, voxel.id);
            imageStore(gbufferTexture, pix, gkey);
        }else{
            gkey = PackGBuffer(uvec3(0u), 0u, 0u, 0u, 0u);
            imageStore(gbufferTexture, pix, gkey);
        }
    }
}